services:
  etl:
    image: python:3.10-slim
    volumes:
      - .:/ETL
    working_dir: /ETL
    command: bash -c "python -m venv /venv && /venv/bin/pip install -r requirements.txt && /venv/bin/python scheduler.py"
